### ISSUE TITLE
'Dataset' object has no attribute 'xls'

### ISSUE THREAD

**Issue by tobifroe** [mishbahr/djangocms-forms#88]
When trying to export form submissions as a Microsoft Excel file, I get an AttributeError. Other export formats work fine.
The traceback looks like this:
> [25/Sep/2020 10:03:44] "POST /admin/djangocms_forms/formsubmission/export/ HTTP/1.1" 200 76
/home/vagrant/project/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1393: RuntimeWarning: DateTimeField FormSubmission.creation_date received a naive datetime (2020-09-25 00:00:00) while time zone support is active.
  RuntimeWarning)
/home/vagrant/project/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1393: RuntimeWarning: DateTimeField FormSubmission.creation_date received a naive datetime (2020-09-26 00:00:00) while time zone support is active. 
  RuntimeWarning)
2020-09-25 10:05:21,005 django.request ERROR    Internal Server Error: /admin/djangocms_forms/formsubmission/export/
Traceback (most recent call last):
  File "/home/vagrant/project/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/vagrant/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vagrant/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/vagrant/project/lib/python3.6/site-packages/djangocms_forms/admin.py", line 105, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/vagrant/project/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/project/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/project/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/home/vagrant/project/lib/python3.6/site-packages/djangocms_forms/admin.py", line 238, in export_view
    getattr(dataset, file_type), {
AttributeError: 'Dataset' object has no attribute 'xls'

Did I miss something while configuring or is there somehting else going on?

**Comment by hakanalpp** [comment]
Facing this issue in tablib 3.0.0 with the following code: 

```
from tablib import Dataset
  
with open('field.json', 'r') as input:
    imported_data = Dataset().load(input.read())
    xx = imported_data.xls
    with open('data.xls', 'wb') as output:
        output.write(xx)
        output.close()
```

The error code:
```
Traceback (most recent call last):
  File "/home/alp/Documents/Yazilim/Prighter/spreadsheet.py", line 5, in <module>
    xx = imported_data.xls
AttributeError: 'Dataset' object has no attribute 'xls'
```

**Comment by wesleyboar** [comment]
You might need to install `tablib` extras to support 'xls'. For more information, see https://github.com/avryhof/djangocms-forms/issues/8.

**Comment by avryhof** [comment]
I'll dig into Excel and YAML support soon, but for now, there is an option to remove them from the interface.

https://github.com/avryhof/djangocms-forms
https://pypi.python.org/pypi/djangocms-forms-maintained/

```pip install --upgrade djsngocms-forms-maintained```
