### ISSUE TITLE
Python 2 Compatible?

### ISSUE THREAD

**Issue by lukyncze** [mishbahr/djangocms-forms#90]
Hello, this happens when i install a plugin and make a migrations. Any ideas?

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "D:\Final-project\env\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "D:\Final-project\env\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "D:\Final-project\env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\Final-project\env\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "D:\Final-project\env\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\lukas\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Final-project\env\lib\site-packages\djangocms_forms\models.py", line 9, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (D:\Final-project\env\lib\site-packages\django\utils\encoding.py)

**Comment by Moon-developer** [comment]
it's because that method has moved to `six` in Django 3 and this library has not been updated in awhile. Hope this helps a bit.

You can fix this by changing the import wherever you get this error,
old code:
```from django.utils.encoding import python_2_unicode_compatible```

Updated code:
```from six import python_2_unicode_compatible```

Go to the mentioned path and edit it, or upgrade all libraries, it should solve the issue. but I can't confirm no other issues will arise since, again, the library is outdated.

**Comment by avryhof** [comment]
We have that fix, too!

https://github.com/avryhof/djangocms-forms
https://pypi.python.org/pypi/djangocms-forms-maintained/

```pip install --upgrade djsngocms-forms-maintained```

**Comment by lukyncze** [comment]
@Moon-developer Thanks! It did not fix the issue unfortunately.

@avryhof Thank you for you comment. But after almost 2 years I won´t test it....

Closing the issue...
